### ISSUE TITLE
v2: server status

### ISSUE THREAD

**Issue by emersion** [emersion/go-imap#498]
- [ ] Plumb context
- [ ] Command pipelining (#554)
- [ ] Expose helpers for `FETCH` and `SEARCH`
- [ ] Expose helper for making a `NumSet` static
- [ ] Add support for `CREATE`, `DELETE`, `RENAME`, `PERMANENTFLAGS` unilateral updates (maybe more?)
- [ ] Add `Server.Shutdown` (#665)
- [x] Add `PREAUTH` greeting
- [x] Add support for `SEARCHRES` (#549)
- [x] Canonicalize message flags and mailbox attrs
- [ ] Add proper NAMESPACE support to imapmemserver (#509)
- [x] Decode header fields and body in SEARCH
- [x] Use `literal8` in response to `FETCH BINARY[]`
- [ ] Consider allowing users to dynamically enable/disable caps
- [ ] Send `FLAGS` updates in imapmemserver (#497)
- [ ] Add more extensions
  - [x] LITERAL+
  - [ ] METADATA
  - [ ] QUOTA
  - [ ] SORT
  - [ ] THREAD

**Comment by sashamelentyev** [comment]
@emersion hello!
When plan add "Plumb context"?
